os:
  - linux
env:
- LOGSENE_TOKEN=test-token
sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
node_js:
#  - "4"
#  - "5"
  - "6"
  - "8"
  - "10"
  - "11"
install:
  - mkdir tmp
  - mkdir mocha-test
  - mkdir test-token
  - npm i 
